### ISSUE TITLE
Peer to peer code review 

### ISSUE THREAD

**Issue by Ofarouq310** [SekoViper/portfolio#5]
### Feedback

Good job!
I love how you used variables for all the colors.
Please, here are a few recommendations we think you should consider.

- I think your styling should be mobile first instead of desktop first. It is always a good practice to style the mobile version of your website before your desktop version.
- Your README file is detailed. You can make it better by including a demo screenshot of your project.
- I think you should consider adding the button inside the form's fieldset and give it "align-self" to center it.

**Comment by SekoViper** [comment]
Great thanks. I will look at them.
